// <auto-generated />
using System;
using AssetFlow.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AssetFlowDbContext))]
    [Migration("20260712060121_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssetFlow.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<int?>("ActorId")
                        .HasColumnType("integer")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("details_json");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.HasKey("LogId")
                        .HasName("pk_activity_logs");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_activity_logs_actor_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_activity_logs_client_id");

                    b.HasIndex("ClientId", "ActorId")
                        .HasDatabaseName("ix_activity_logs_client_id_actor_id");

                    b.HasIndex("ClientId", "EntityType", "EntityId")
                        .HasDatabaseName("ix_activity_logs_client_id_entity_type_entity_id");

                    b.ToTable("activity_logs");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.Asset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("asset_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssetId"));

                    b.Property<decimal?>("AcquisitionCost")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("acquisition_cost");

                    b.Property<DateOnly?>("AcquisitionDate")
                        .HasColumnType("date")
                        .HasColumnName("acquisition_date");

                    b.Property<string>("AssetTag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asset_tag");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("Condition")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("condition");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<int?>("CurrentHolderDepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("current_holder_department_id");

                    b.Property<int?>("CurrentHolderEmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("current_holder_employee_id");

                    b.Property<string>("CustomFieldValuesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_field_values_json");

                    b.Property<bool>("IsBookable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_bookable");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("QrCode")
                        .HasColumnType("text")
                        .HasColumnName("qr_code");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AssetId")
                        .HasName("pk_assets");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_assets_category_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_assets_client_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_assets_created_by");

                    b.HasIndex("CurrentHolderDepartmentId")
                        .HasDatabaseName("ix_assets_current_holder_department_id");

                    b.HasIndex("CurrentHolderEmployeeId")
                        .HasDatabaseName("ix_assets_current_holder_employee_id");

                    b.HasIndex("ClientId", "AssetTag")
                        .IsUnique()
                        .HasDatabaseName("ix_assets_client_id_asset_tag");

                    b.HasIndex("ClientId", "CategoryId")
                        .HasDatabaseName("ix_assets_client_id_category_id");

                    b.HasIndex("ClientId", "Location")
                        .HasDatabaseName("ix_assets_client_id_location");

                    b.HasIndex("ClientId", "Status")
                        .HasDatabaseName("ix_assets_client_id_status");

                    b.ToTable("assets");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.AssetAllocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("allocation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AllocationId"));

                    b.Property<DateOnly?>("ActualReturnDate")
                        .HasColumnType("date")
                        .HasColumnName("actual_return_date");

                    b.Property<DateTime>("AllocatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("allocated_at");

                    b.Property<int>("AllocatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("allocated_by");

                    b.Property<int>("AssetId")
                        .HasColumnType("integer")
                        .HasColumnName("asset_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly?>("ExpectedReturnDate")
                        .HasColumnType("date")
                        .HasColumnName("expected_return_date");

                    b.Property<string>("ReturnConditionNotes")
                        .HasColumnType("text")
                        .HasColumnName("return_condition_notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("AllocationId")
                        .HasName("pk_asset_allocations");

                    b.HasIndex("AllocatedBy")
                        .HasDatabaseName("ix_asset_allocations_allocated_by");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_asset_allocations_asset_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_asset_allocations_client_id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_asset_allocations_department_id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_asset_allocations_employee_id");

                    b.HasIndex("ClientId", "AssetId")
                        .IsUnique()
                        .HasDatabaseName("uq_one_active_allocation_per_asset")
                        .HasFilter("\"status\" = 'Active'");

                    b.HasIndex("ClientId", "EmployeeId")
                        .HasDatabaseName("ix_asset_allocations_client_id_employee_id");

                    b.HasIndex("ClientId", "ExpectedReturnDate")
                        .HasDatabaseName("idx_allocations_overdue")
                        .HasFilter("\"status\" = 'Active'");

                    b.ToTable("asset_allocations", t =>
                        {
                            t.HasCheckConstraint("chk_holder_present", "\"employee_id\" IS NOT NULL OR \"department_id\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.AssetCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomFieldsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_fields_json");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("CategoryId")
                        .HasName("pk_asset_categories");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_asset_categories_client_id");

                    b.HasIndex("ClientId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_categories_client_id_name");

                    b.ToTable("asset_categories");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.AssetDocument", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocumentId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("integer")
                        .HasColumnName("asset_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("FileType")
                        .HasColumnType("text")
                        .HasColumnName("file_type");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<int?>("UploadedBy")
                        .HasColumnType("integer")
                        .HasColumnName("uploaded_by");

                    b.Property<int?>("UploadedByEmployeeEmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("uploaded_by_employee_employee_id");

                    b.HasKey("DocumentId")
                        .HasName("pk_asset_documents");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_asset_documents_asset_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_asset_documents_client_id");

                    b.HasIndex("UploadedByEmployeeEmployeeId")
                        .HasDatabaseName("ix_asset_documents_uploaded_by_employee_employee_id");

                    b.ToTable("asset_documents");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.AssetStatusHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("history_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoryId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("integer")
                        .HasColumnName("asset_id");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<int?>("ChangedBy")
                        .HasColumnType("integer")
                        .HasColumnName("changed_by");

                    b.Property<int?>("ChangedByEmployeeEmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("changed_by_employee_employee_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("from_status");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("to_status");

                    b.HasKey("HistoryId")
                        .HasName("pk_asset_status_history");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_asset_status_history_asset_id");

                    b.HasIndex("ChangedByEmployeeEmployeeId")
                        .HasDatabaseName("ix_asset_status_history_changed_by_employee_employee_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_asset_status_history_client_id");

                    b.ToTable("asset_status_history");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.AuditCycle", b =>
                {
                    b.Property<int>("AuditCycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("audit_cycle_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AuditCycleId"));

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<int?>("ClosedBy")
                        .HasColumnType("integer")
                        .HasColumnName("closed_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("ScopeDepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("scope_department_id");

                    b.Property<string>("ScopeLocation")
                        .HasColumnType("text")
                        .HasColumnName("scope_location");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("AuditCycleId")
                        .HasName("pk_audit_cycles");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_audit_cycles_client_id");

                    b.HasIndex("ClosedBy")
                        .HasDatabaseName("ix_audit_cycles_closed_by");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_audit_cycles_created_by");

                    b.HasIndex("ScopeDepartmentId")
                        .HasDatabaseName("ix_audit_cycles_scope_department_id");

                    b.ToTable("audit_cycles", t =>
                        {
                            t.HasCheckConstraint("chk_audit_dates", "\"end_date\" >= \"start_date\"");
                        });
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.AuditCycleAsset", b =>
                {
                    b.Property<int>("AuditCycleAssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("audit_cycle_asset_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AuditCycleAssetId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("integer")
                        .HasColumnName("asset_id");

                    b.Property<int>("AuditCycleId")
                        .HasColumnType("integer")
                        .HasColumnName("audit_cycle_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("verification_status");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<int?>("VerifiedBy")
                        .HasColumnType("integer")
                        .HasColumnName("verified_by");

                    b.HasKey("AuditCycleAssetId")
                        .HasName("pk_audit_cycle_assets");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_audit_cycle_assets_asset_id");

                    b.HasIndex("AuditCycleId")
                        .HasDatabaseName("ix_audit_cycle_assets_audit_cycle_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_audit_cycle_assets_client_id");

                    b.HasIndex("VerifiedBy")
                        .HasDatabaseName("ix_audit_cycle_assets_verified_by");

                    b.HasIndex("ClientId", "AuditCycleId", "AssetId")
                        .IsUnique()
                        .HasDatabaseName("ix_audit_cycle_assets_client_id_audit_cycle_id_asset_id");

                    b.ToTable("audit_cycle_assets");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.AuditCycleAuditor", b =>
                {
                    b.Property<int>("AuditCycleId")
                        .HasColumnType("integer")
                        .HasColumnName("audit_cycle_id");

                    b.Property<int>("AuditorId")
                        .HasColumnType("integer")
                        .HasColumnName("auditor_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.HasKey("AuditCycleId", "AuditorId")
                        .HasName("pk_audit_cycle_auditors");

                    b.HasIndex("AuditorId")
                        .HasDatabaseName("ix_audit_cycle_auditors_auditor_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_audit_cycle_auditors_client_id");

                    b.ToTable("audit_cycle_auditors");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_email");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("plan");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subdomain");

                    b.Property<DateTime?>("SubscriptionExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscription_expires_at");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_ends_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ClientId")
                        .HasName("pk_clients");

                    b.HasIndex("ContactEmail")
                        .HasDatabaseName("ix_clients_contact_email");

                    b.HasIndex("Subdomain")
                        .IsUnique()
                        .HasDatabaseName("ix_clients_subdomain");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmentId"));

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DepartmentHeadId")
                        .HasColumnType("integer")
                        .HasColumnName("department_head_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("ParentDepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_department_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("DepartmentId")
                        .HasName("pk_departments");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_departments_client_id");

                    b.HasIndex("DepartmentHeadId")
                        .HasDatabaseName("ix_departments_department_head_id");

                    b.HasIndex("ParentDepartmentId")
                        .HasDatabaseName("ix_departments_parent_department_id");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.DiscrepancyReport", b =>
                {
                    b.Property<int>("DiscrepancyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("discrepancy_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DiscrepancyId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("integer")
                        .HasColumnName("asset_id");

                    b.Property<int>("AuditCycleId")
                        .HasColumnType("integer")
                        .HasColumnName("audit_cycle_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DiscrepancyType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("discrepancy_type");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("ResolutionStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("resolution_status");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<int?>("ResolvedBy")
                        .HasColumnType("integer")
                        .HasColumnName("resolved_by");

                    b.HasKey("DiscrepancyId")
                        .HasName("pk_discrepancy_reports");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_discrepancy_reports_asset_id");

                    b.HasIndex("AuditCycleId")
                        .HasDatabaseName("ix_discrepancy_reports_audit_cycle_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_discrepancy_reports_client_id");

                    b.HasIndex("ResolvedBy")
                        .HasDatabaseName("ix_discrepancy_reports_resolved_by");

                    b.ToTable("discrepancy_reports");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeId"));

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("EmployeeId")
                        .HasName("pk_employees");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_employees_client_id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_employees_department_id");

                    b.HasIndex("ClientId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_client_id_email");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.MaintenanceRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("request_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer")
                        .HasColumnName("approved_by");

                    b.Property<int>("AssetId")
                        .HasColumnType("integer")
                        .HasColumnName("asset_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issue_description");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("priority");

                    b.Property<int>("RaisedBy")
                        .HasColumnType("integer")
                        .HasColumnName("raised_by");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("TechnicianName")
                        .HasColumnType("text")
                        .HasColumnName("technician_name");

                    b.HasKey("RequestId")
                        .HasName("pk_maintenance_requests");

                    b.HasIndex("ApprovedBy")
                        .HasDatabaseName("ix_maintenance_requests_approved_by");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_maintenance_requests_asset_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_maintenance_requests_client_id");

                    b.HasIndex("RaisedBy")
                        .HasDatabaseName("ix_maintenance_requests_raised_by");

                    b.HasIndex("ClientId", "AssetId")
                        .HasDatabaseName("ix_maintenance_requests_client_id_asset_id");

                    b.HasIndex("ClientId", "Status")
                        .HasDatabaseName("ix_maintenance_requests_client_id_status");

                    b.ToTable("maintenance_requests");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.MaintenanceStatusLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<int?>("ChangedBy")
                        .HasColumnType("integer")
                        .HasColumnName("changed_by");

                    b.Property<int?>("ChangedByEmployeeEmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("changed_by_employee_employee_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("from_status");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer")
                        .HasColumnName("request_id");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("to_status");

                    b.HasKey("LogId")
                        .HasName("pk_maintenance_status_log");

                    b.HasIndex("ChangedByEmployeeEmployeeId")
                        .HasDatabaseName("ix_maintenance_status_log_changed_by_employee_employee_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_maintenance_status_log_client_id");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("ix_maintenance_status_log_request_id");

                    b.ToTable("maintenance_status_log");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("notification_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("RecipientId")
                        .HasColumnType("integer")
                        .HasColumnName("recipient_id");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("integer")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasColumnType("text")
                        .HasColumnName("reference_type");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("NotificationId")
                        .HasName("pk_notifications");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_notifications_client_id");

                    b.HasIndex("RecipientId")
                        .HasDatabaseName("ix_notifications_recipient_id");

                    b.HasIndex("ClientId", "RecipientId", "IsRead")
                        .HasDatabaseName("ix_notifications_client_id_recipient_id_is_read");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.ResourceBooking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("booking_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookingId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("integer")
                        .HasColumnName("asset_id");

                    b.Property<int>("BookedBy")
                        .HasColumnType("integer")
                        .HasColumnName("booked_by");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("BookingId")
                        .HasName("pk_resource_bookings");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_resource_bookings_asset_id");

                    b.HasIndex("BookedBy")
                        .HasDatabaseName("ix_resource_bookings_booked_by");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_resource_bookings_client_id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_resource_bookings_department_id");

                    b.HasIndex("ClientId", "AssetId", "StartTime", "EndTime")
                        .HasDatabaseName("ix_resource_bookings_client_id_asset_id_start_time_end_time");

                    b.ToTable("resource_bookings", t =>
                        {
                            t.HasCheckConstraint("chk_booking_time_order", "\"end_time\" > \"start_time\"");
                        });
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.RoleChangeLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<int>("ChangedBy")
                        .HasColumnType("integer")
                        .HasColumnName("changed_by");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<string>("NewRole")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("new_role");

                    b.Property<string>("OldRole")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("old_role");

                    b.HasKey("LogId")
                        .HasName("pk_role_change_log");

                    b.HasIndex("ChangedBy")
                        .HasDatabaseName("ix_role_change_log_changed_by");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_role_change_log_client_id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_role_change_log_employee_id");

                    b.ToTable("role_change_log");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.TransferRequest", b =>
                {
                    b.Property<int>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("transfer_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransferId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer")
                        .HasColumnName("approved_by");

                    b.Property<int>("AssetId")
                        .HasColumnType("integer")
                        .HasColumnName("asset_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<int?>("FromEmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("from_employee_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<int>("RequestedBy")
                        .HasColumnType("integer")
                        .HasColumnName("requested_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<int>("ToEmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("to_employee_id");

                    b.HasKey("TransferId")
                        .HasName("pk_transfer_requests");

                    b.HasIndex("ApprovedBy")
                        .HasDatabaseName("ix_transfer_requests_approved_by");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_transfer_requests_asset_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_transfer_requests_client_id");

                    b.HasIndex("FromEmployeeId")
                        .HasDatabaseName("ix_transfer_requests_from_employee_id");

                    b.HasIndex("RequestedBy")
                        .HasDatabaseName("ix_transfer_requests_requested_by");

                    b.HasIndex("ToEmployeeId")
                        .HasDatabaseName("ix_transfer_requests_to_employee_id");

                    b.ToTable("transfer_requests");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.ActivityLog", b =>
                {
                    b.HasOne("AssetFlow.Domain.Entities.Employee", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_activity_logs_employees_actor_id");

                    b.HasOne("AssetFlow.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_logs_clients_client_id");

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.Asset", b =>
                {
                    b.HasOne("AssetFlow.Domain.Entities.AssetCategory", "Category")
                        .WithMany("Assets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assets_asset_categories_category_id");

                    b.HasOne("AssetFlow.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assets_clients_client_id");

                    b.HasOne("AssetFlow.Domain.Entities.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_assets_employees_created_by");

                    b.HasOne("AssetFlow.Domain.Entities.Department", "CurrentHolderDepartment")
                        .WithMany()
                        .HasForeignKey("CurrentHolderDepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_assets_departments_current_holder_department_id");

                    b.HasOne("AssetFlow.Domain.Entities.Employee", "CurrentHolderEmployee")
                        .WithMany()
                        .HasForeignKey("CurrentHolderEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_assets_employees_current_holder_employee_id");

                    b.Navigation("Category");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("CurrentHolderDepartment");

                    b.Navigation("CurrentHolderEmployee");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.AssetAllocation", b =>
                {
                    b.HasOne("AssetFlow.Domain.Entities.Employee", "AllocatedByEmployee")
                        .WithMany()
                        .HasForeignKey("AllocatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_asset_allocations_employees_allocated_by");

                    b.HasOne("AssetFlow.Domain.Entities.Asset", "Asset")
                        .WithMany("Allocations")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_asset_allocations_assets_asset_id");

                    b.HasOne("AssetFlow.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_asset_allocations_clients_client_id");

                    b.HasOne("AssetFlow.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_asset_allocations_departments_department_id");

                    b.HasOne("AssetFlow.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_asset_allocations_employees_employee_id");

                    b.Navigation("AllocatedByEmployee");

                    b.Navigation("Asset");

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.AssetCategory", b =>
                {
                    b.HasOne("AssetFlow.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_asset_categories_clients_client_id");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.AssetDocument", b =>
                {
                    b.HasOne("AssetFlow.Domain.Entities.Asset", "Asset")
                        .WithMany("Documents")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asset_documents_assets_asset_id");

                    b.HasOne("AssetFlow.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_asset_documents_clients_client_id");

                    b.HasOne("AssetFlow.Domain.Entities.Employee", "UploadedByEmployee")
                        .WithMany()
                        .HasForeignKey("UploadedByEmployeeEmployeeId")
                        .HasConstraintName("fk_asset_documents_employees_uploaded_by_employee_employee_id");

                    b.Navigation("Asset");

                    b.Navigation("UploadedByEmployee");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.AssetStatusHistory", b =>
                {
                    b.HasOne("AssetFlow.Domain.Entities.Asset", "Asset")
                        .WithMany("StatusHistory")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asset_status_history_assets_asset_id");

                    b.HasOne("AssetFlow.Domain.Entities.Employee", "ChangedByEmployee")
                        .WithMany()
                        .HasForeignKey("ChangedByEmployeeEmployeeId")
                        .HasConstraintName("fk_asset_status_history_employees_changed_by_employee_employee~");

                    b.HasOne("AssetFlow.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_asset_status_history_clients_client_id");

                    b.Navigation("Asset");

                    b.Navigation("ChangedByEmployee");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.AuditCycle", b =>
                {
                    b.HasOne("AssetFlow.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_cycles_clients_client_id");

                    b.HasOne("AssetFlow.Domain.Entities.Employee", "ClosedByEmployee")
                        .WithMany()
                        .HasForeignKey("ClosedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_cycles_employees_closed_by");

                    b.HasOne("AssetFlow.Domain.Entities.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_cycles_employees_created_by");

                    b.HasOne("AssetFlow.Domain.Entities.Department", "ScopeDepartment")
                        .WithMany()
                        .HasForeignKey("ScopeDepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_cycles_departments_scope_department_id");

                    b.Navigation("ClosedByEmployee");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("ScopeDepartment");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.AuditCycleAsset", b =>
                {
                    b.HasOne("AssetFlow.Domain.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_cycle_assets_assets_asset_id");

                    b.HasOne("AssetFlow.Domain.Entities.AuditCycle", "AuditCycle")
                        .WithMany("ScopedAssets")
                        .HasForeignKey("AuditCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audit_cycle_assets_audit_cycles_audit_cycle_id");

                    b.HasOne("AssetFlow.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_cycle_assets_clients_client_id");

                    b.HasOne("AssetFlow.Domain.Entities.Employee", "VerifiedByEmployee")
                        .WithMany()
                        .HasForeignKey("VerifiedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_cycle_assets_employees_verified_by");

                    b.Navigation("Asset");

                    b.Navigation("AuditCycle");

                    b.Navigation("VerifiedByEmployee");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.AuditCycleAuditor", b =>
                {
                    b.HasOne("AssetFlow.Domain.Entities.AuditCycle", "AuditCycle")
                        .WithMany("Auditors")
                        .HasForeignKey("AuditCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audit_cycle_auditors_audit_cycles_audit_cycle_id");

                    b.HasOne("AssetFlow.Domain.Entities.Employee", "Auditor")
                        .WithMany()
                        .HasForeignKey("AuditorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_cycle_auditors_employees_auditor_id");

                    b.HasOne("AssetFlow.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_cycle_auditors_clients_client_id");

                    b.Navigation("AuditCycle");

                    b.Navigation("Auditor");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.Department", b =>
                {
                    b.HasOne("AssetFlow.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_departments_clients_client_id");

                    b.HasOne("AssetFlow.Domain.Entities.Employee", "DepartmentHead")
                        .WithMany()
                        .HasForeignKey("DepartmentHeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_departments_employees_department_head_id");

                    b.HasOne("AssetFlow.Domain.Entities.Department", "ParentDepartment")
                        .WithMany("ChildDepartments")
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_departments_departments_parent_department_id");

                    b.Navigation("DepartmentHead");

                    b.Navigation("ParentDepartment");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.DiscrepancyReport", b =>
                {
                    b.HasOne("AssetFlow.Domain.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_discrepancy_reports_assets_asset_id");

                    b.HasOne("AssetFlow.Domain.Entities.AuditCycle", "AuditCycle")
                        .WithMany("DiscrepancyReports")
                        .HasForeignKey("AuditCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_discrepancy_reports_audit_cycles_audit_cycle_id");

                    b.HasOne("AssetFlow.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_discrepancy_reports_clients_client_id");

                    b.HasOne("AssetFlow.Domain.Entities.Employee", "ResolvedByEmployee")
                        .WithMany()
                        .HasForeignKey("ResolvedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_discrepancy_reports_employees_resolved_by");

                    b.Navigation("Asset");

                    b.Navigation("AuditCycle");

                    b.Navigation("ResolvedByEmployee");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.Employee", b =>
                {
                    b.HasOne("AssetFlow.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employees_clients_client_id");

                    b.HasOne("AssetFlow.Domain.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_employees_departments_department_id");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.MaintenanceRequest", b =>
                {
                    b.HasOne("AssetFlow.Domain.Entities.Employee", "ApprovedByEmployee")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_maintenance_requests_employees_approved_by");

                    b.HasOne("AssetFlow.Domain.Entities.Asset", "Asset")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_requests_assets_asset_id");

                    b.HasOne("AssetFlow.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_requests_clients_client_id");

                    b.HasOne("AssetFlow.Domain.Entities.Employee", "RaisedByEmployee")
                        .WithMany()
                        .HasForeignKey("RaisedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_requests_employees_raised_by");

                    b.Navigation("ApprovedByEmployee");

                    b.Navigation("Asset");

                    b.Navigation("RaisedByEmployee");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.MaintenanceStatusLog", b =>
                {
                    b.HasOne("AssetFlow.Domain.Entities.Employee", "ChangedByEmployee")
                        .WithMany()
                        .HasForeignKey("ChangedByEmployeeEmployeeId")
                        .HasConstraintName("fk_maintenance_status_log_employees_changed_by_employee_employ~");

                    b.HasOne("AssetFlow.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_status_log_clients_client_id");

                    b.HasOne("AssetFlow.Domain.Entities.MaintenanceRequest", "Request")
                        .WithMany("StatusLogs")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_status_log_maintenance_requests_request_id");

                    b.Navigation("ChangedByEmployee");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.Notification", b =>
                {
                    b.HasOne("AssetFlow.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_clients_client_id");

                    b.HasOne("AssetFlow.Domain.Entities.Employee", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_employees_recipient_id");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.ResourceBooking", b =>
                {
                    b.HasOne("AssetFlow.Domain.Entities.Asset", "Asset")
                        .WithMany("Bookings")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resource_bookings_assets_asset_id");

                    b.HasOne("AssetFlow.Domain.Entities.Employee", "BookedByEmployee")
                        .WithMany()
                        .HasForeignKey("BookedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resource_bookings_employees_booked_by");

                    b.HasOne("AssetFlow.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resource_bookings_clients_client_id");

                    b.HasOne("AssetFlow.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_resource_bookings_departments_department_id");

                    b.Navigation("Asset");

                    b.Navigation("BookedByEmployee");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.RoleChangeLog", b =>
                {
                    b.HasOne("AssetFlow.Domain.Entities.Employee", "ChangedByEmployee")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_change_log_employees_changed_by");

                    b.HasOne("AssetFlow.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_change_log_clients_client_id");

                    b.HasOne("AssetFlow.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_change_log_employees_employee_id");

                    b.Navigation("ChangedByEmployee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.TransferRequest", b =>
                {
                    b.HasOne("AssetFlow.Domain.Entities.Employee", "ApprovedByEmployee")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transfer_requests_employees_approved_by");

                    b.HasOne("AssetFlow.Domain.Entities.Asset", "Asset")
                        .WithMany("TransferRequests")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transfer_requests_assets_asset_id");

                    b.HasOne("AssetFlow.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transfer_requests_clients_client_id");

                    b.HasOne("AssetFlow.Domain.Entities.Employee", "FromEmployee")
                        .WithMany()
                        .HasForeignKey("FromEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transfer_requests_employees_from_employee_id");

                    b.HasOne("AssetFlow.Domain.Entities.Employee", "RequestedByEmployee")
                        .WithMany()
                        .HasForeignKey("RequestedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transfer_requests_employees_requested_by");

                    b.HasOne("AssetFlow.Domain.Entities.Employee", "ToEmployee")
                        .WithMany()
                        .HasForeignKey("ToEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transfer_requests_employees_to_employee_id");

                    b.Navigation("ApprovedByEmployee");

                    b.Navigation("Asset");

                    b.Navigation("FromEmployee");

                    b.Navigation("RequestedByEmployee");

                    b.Navigation("ToEmployee");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.Asset", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Bookings");

                    b.Navigation("Documents");

                    b.Navigation("MaintenanceRequests");

                    b.Navigation("StatusHistory");

                    b.Navigation("TransferRequests");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.AssetCategory", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.AuditCycle", b =>
                {
                    b.Navigation("Auditors");

                    b.Navigation("DiscrepancyReports");

                    b.Navigation("ScopedAssets");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.Department", b =>
                {
                    b.Navigation("ChildDepartments");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("AssetFlow.Domain.Entities.MaintenanceRequest", b =>
                {
                    b.Navigation("StatusLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
